version: 2

.build-script-template:
  default: &build-script
    - checkout
    - run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build .
        ctest -C Debug

workflows:
  version: 2
  build-and-test:
    jobs:
      # GCC
      - gcc-latest
      - gcc-7.2
      - gcc-6.4
      - gcc-5.5
      - gcc-4.9
      - gcc-4.8
      - gcc-4.6
      - gcc-4.4
      # Clang
      - clang-latest
      - clang-6.0
      - clang-5.0
      - clang-4.0
      - clang-3.8
      - clang-3.6
      - clang-3.4

jobs:
  # GCC
  gcc-latest:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-latest
  gcc-7.2:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-7.2
  gcc-6.4:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-6.4
  gcc-5.5:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-5.5
  gcc-4.9:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-4.9
  gcc-4.8:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-4.8
  gcc-4.6:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-4.6
  gcc-4.4:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-4.4
  # Clang
  clang-latest:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:clang-latest
  clang-6.0:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:clang-6.0
  clang-5.0:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:clang-5.0
  clang-4.0:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:clang-4.0
  clang-3.8:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:clang-3.8
  clang-3.6:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:clang-3.6
  clang-3.4:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:clang-3.4
