#ifndef BICOMC_DETAIL_COMPILER_GCC_H__
#define BICOMC_DETAIL_COMPILER_GCC_H__

#if !defined(__GNUC__)
#	error "compiler is not gcc"
#endif // !def __GNUC__

#define BICOMC_EXPORT __attribute__((visibility("default")))

#define BICOMC_IS_NULLPTR_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_STATIC_ASSERT_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_THREAD_SAFE_STATIC_INIT_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__) || __GNUC__ >= 4)
#define BICOMC_IS_CONSTEXPR_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_NOEXCEPT_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_EXPLICITY_DEFAULT_DELETE_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_MOVE_SEMANTIC_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_VARIADIC_TEMPLATE_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_CHAR_16_32_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_STD_INT_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_TYPE_TRAITS_SUPPORT_COMPILER	\
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_MUTEX_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_CODE_CVT_UTF8_SUPPORT_COMPILER \
	((__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__)) && __GNUC__ > 4)
#define BICOMC_IS_EXTENED_EQUAL_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))
#define BICOMC_IS_ARRAY_SUPPORT_COMPILER \
	(__cplusplus >= 201103L || defined(__GXX_EXPERIMENTAL_CXX0X__))

#endif // !def BICOMC_DETAIL_COMPILER_GCC_H__
